### ISSUE TITLE
Build and test Erlang exercises with Rebar3

### ISSUE THREAD

**Issue by lpil** [exercism/xerlang#106]
Now that Rebar 3 is the official build tool of Erlang should we use it here?

It would be a little friendlier as the command would be 

``` sh
rebar3 eunit
```

instead of 

``` sh
erl -make
erl -noshell -eval "eunit:test(accumulate, [verbose])" -s init stop
```

This would require changing the exercises to use the Erlang OTP project directory structure, which I think would be a good thing.

**Comment by kytrinyx** [comment]
@tmcgilchrist @lehoff @NobbZ any thoughts on rebar 3 (and Erlang OTP project directory structure)?

**Comment by NobbZ** [comment]
I think, migrating to rebar were a good thing as it would make most things much easier. But it would require the student to install just another tool (that he might want to use anyway) since `rebar3` might be the officially supposed build tool, but it is not bundled with current versions of the erlang compiler and run time, this is true for debian based distributions at least.

Also I think this should be a migration that happens all at once, and not step by step. I can remember the confusion over at the haskell-track when they switched from `runhaskell` to `stack`, and the build tool used was different in every other exercise.

Also I do think, that the track should be revised in general, and I am unsure if we should do this revision in a single step while migrating to `rebar` or independent from that. I do tend towards doing it in seperate steps though.

**Comment by kytrinyx** [comment]
> I do tend towards doing it in seperate steps though.

Likewise. I think that it would be easier to make one transition at a time.
